name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  start-test-stop-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Start temporary environment
        run: docker compose up -d

      - name: Wait for app to start
        run: sleep 10

      - name: Test the web page
        run: curl -f http://localhost:8080

      - name: Stop and remove environment
        if: always()
        run: docker compose down